import { Movie } from "@/types/movie.type";

export const Movies: Movie[] = [
  {
    id: "ghibli-001",
    movie_id: 129,
    language: "pt",
    title: "A Viagem de Chihiro",
    description: "Durante a mudança da família para um novo bairro, a menina Chihiro de 10 anos entra em um mundo mágico governado por deuses, bruxas e espíritos, onde humanos são transformados em animais.",
    poster: "https://image.tmdb.org/t/p/original/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/bSXfU4dwZyBA1vMmXvejdRXBvuF.jpg",
    release_date: "Sáb, 20/07/2001",
    rank: 8.5,
  },
  {
    id: "ghibli-002",
    movie_id: 128,
    language: "pt",
    title: "Meu Amigo Totoro",
    description: "Duas irmãs se mudam para o interior com o pai para ficar perto da mãe hospitalizada e acabam fazendo amizade com Totoro, o espírito mágico da floresta.",
    poster: "https://image.tmdb.org/t/p/original/rtGDOeG9LzoerkDGZF9dnVeLppL.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    release_date: "Sáb, 16/04/1988",
    rank: 8.4,
  },
  {
    id: "ghibli-003",
    movie_id: 4935,
    language: "pt",
    title: "O Castelo Animado",
    description: "Quando uma jovem insegura é amaldiçoada por uma bruxa invejosa e transformada em velha, sua única chance de quebrar o feitiço está nas mãos de um jovem mágico excêntrico.",
    poster: "https://image.tmdb.org/t/p/original/TkTP5VHNOqCg9USYi0NMGkvGD6J.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/jVVSoaHHgvBxGgOxZKqzAcFVqfQ.jpg",
    release_date: "Sáb, 20/11/2004",
    rank: 8.4,
  },
  {
    id: "ghibli-004",
    movie_id: 756,
    language: "pt",
    title: "Princesa Mononoke",
    description: "Em busca da cura para uma maldição, Ashitaka se vê no meio de uma guerra entre os deuses da floresta e uma colônia de mineração que destrói a natureza.",
    poster: "https://image.tmdb.org/t/p/original/jHnGYOGFGAGPgplbkGZcUQWHl00.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/liW8KCRMuMhafPiMEH3NMqRfmXj.jpg",
    release_date: "Sáb, 12/07/1997",
    rank: 8.3,
  },
  {
    id: "ghibli-005",
    movie_id: 16859,
    language: "pt",
    title: "O Serviço de Entregas da Kiki",
    description: "Uma jovem bruxa, no seu ano obrigatório de vida independente, descobre que a nova cidade traz muitos desafios enquanto sustenta a si mesma com um serviço de entregas aéreas.",
    poster: "https://image.tmdb.org/t/p/original/5pHSmFPCmh21hOjgDgvFHNjxpwd.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/54tRDT1xZMkO3Qa3alyBLfmkDmR.jpg",
    release_date: "Sex, 29/07/1989",
    rank: 7.9,
  },
  {
    id: "ghibli-006",
    movie_id: 12477,
    language: "pt",
    title: "Túmulo dos Vagalumes",
    description: "Um retrato devastador do custo humano da guerra, visto pelos olhos de dois jovens irmãos japoneses lutando para sobreviver nos últimos meses da Segunda Guerra Mundial.",
    poster: "https://image.tmdb.org/t/p/original/k9tv1rXZbOhH7sPjMtDMaMbzpOo.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/vkRWhEFkiZljEpJDzRdWnMhVDLB.jpg",
    release_date: "Sáb, 16/04/1988",
    rank: 8.5,
  },
];